spring:
  application:
    name: tms-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
